#!/bin/bash

scriptpath="$(readlink -f "$0")"
workdir="${scriptpath%/*}"
cd "${workdir}/.."

echo "Render deployment template with variables":
python3 ci/scripts/render_templates.py deployment.yml.j2 \
                                --api_port="$API_PORT" \
                                --database_connection_string="$DATABASE_CONNECTION_STRING" \
                                --image="europe-central2-docker.pkg.dev/$IMAGE_REPOSITORY:$tag"
                                                               


                                                            